table dClientes
	lineageTag: ce7c16dc-b596-45ef-b4bf-dee68841b7eb

	column id_cliente
		dataType: string
		lineageTag: f5886f6a-82e8-43ab-a061-e8f360aa1efc
		summarizeBy: none
		sourceColumn: id_cliente

		annotation SummarizationSetBy = Automatic

	column idade
		dataType: int64
		formatString: 0
		lineageTag: c4c5aa00-b23b-471f-bbfb-15b7d920795a
		summarizeBy: sum
		sourceColumn: idade

		annotation SummarizationSetBy = Automatic

	column cidade
		dataType: string
		lineageTag: 30966cf8-906a-44df-a893-e2c270f70a7c
		summarizeBy: none
		sourceColumn: cidade

		annotation SummarizationSetBy = Automatic

	column renda_mensal
		dataType: double
		lineageTag: 0d925313-9f84-4a1d-a29b-7e0b90522228
		summarizeBy: sum
		sourceColumn: renda_mensal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column faixa_renda
		dataType: string
		lineageTag: 1aceceee-1837-48eb-9943-bfa1cb850ce6
		summarizeBy: none
		sourceColumn: faixa_renda

		annotation SummarizationSetBy = Automatic

	column faixa_etaria
		dataType: string
		lineageTag: 3a5ab0e0-6aab-4eb1-a16f-8817ac2b7196
		summarizeBy: none
		sourceColumn: faixa_etaria

		annotation SummarizationSetBy = Automatic

	column dt_pri_contracao
		dataType: dateTime
		formatString: Short Date
		lineageTag: 29e2ad97-c400-4a4b-8569-2a09641ef7bd
		summarizeBy: none
		sourceColumn: dt_pri_contracao

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition dClientes = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("D:\Meu Drive\00. Cases\case_loft_202512\input\star_schema\clientes.xlsx"), null, true),
				    clentes_Sheet = Fonte{[Item="clentes",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(clentes_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"id_cliente", type text}, {"idade", Int64.Type}, {"cidade", type text}, {"renda_mensal", type number}, {"faixa_renda", type text}, {"faixa_etaria", type text}, {"dt_pri_contracao", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

