table dContratos
	lineageTag: 27cc1609-13e1-4775-98bc-33f1fd9efe9c

	column id_contrato
		dataType: string
		lineageTag: 8cc8d2b9-afe2-4a04-9b2b-89bd9a53f8a7
		summarizeBy: none
		sourceColumn: id_contrato

		annotation SummarizationSetBy = Automatic

	column id_cliente
		dataType: string
		lineageTag: dd1a0900-ca72-42ee-a5f4-51effbcc3c1a
		summarizeBy: none
		sourceColumn: id_cliente

		annotation SummarizationSetBy = Automatic

	column vlr_contrato
		dataType: double
		lineageTag: 47f523f1-2fca-463f-ae8a-f6a84e7cf9fc
		summarizeBy: sum
		sourceColumn: vlr_contrato

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column st_pagto
		dataType: string
		lineageTag: 9f17874b-ca30-426b-affa-ec3b948f0cb4
		summarizeBy: none
		sourceColumn: st_pagto

		annotation SummarizationSetBy = Automatic

	column dt_contratacao
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4f848295-34d0-478c-b825-23ad3d6fea6b
		summarizeBy: none
		sourceColumn: dt_contratacao

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column faixa_atraso
		dataType: string
		lineageTag: 0210dd88-3e33-4a3b-8c23-254ea624dc72
		summarizeBy: none
		sourceColumn: faixa_atraso

		annotation SummarizationSetBy = Automatic

	partition dContratos = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("D:\Meu Drive\00. Cases\case_loft_202512\input\star_schema\contratos.xlsx"), null, true),
				    contratos_Sheet = Fonte{[Item="contratos",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(contratos_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"id_contrato", type text}, {"id_cliente", type text}, {"vlr_contrato", type number}, {"st_pagto", type text}, {"dt_contratacao", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

